### PR TITLE
if invalid adress + workername = 40

### PR DESCRIPTION
**Pull request by sennevb**
if invalid adress + workername = 40 chars, it doesnt get authenticated..

### CODE REVIEW

**Comment by aayanl** [comment]
+1

**Comment by aayanl** [comment]
though indentations need to be fixed

**Comment by sennevb** [comment]
@aayanl what do i need to fix?

**Comment by sennevb** [comment]
Removed 40 chars in paymentprocessor, thanks to @hellcatz  for letting me know

**Pull request merged**
