### PR TITLE
Major Updates 2

### PR DESCRIPTION
**Pull request by hellcatz**
major: added support for komodo, zcash, zclassic, (zdash not tested)
coins: added requireShielding boolean
coins: updated zcash_testnet founders addresses
configs: added komodo_example.conf
api.js: added payments json api call
stats.js: improved getTotalSharesByAdress to support multiple coins.
stats.js: report more collected stats
stats.js: report payment stats
stats.js: optimizations to historical data saving
paymentProcessor.js: added requireShielding support
paymentProcessor.js: added support to pay directly from komodo pool address without shielding first
paymentProcessor.js: lower tx fee reserve for komodo to 0.00005 KMD
paymentProcessor.js: tx fee reserve for all coins is 0.0004
paymentProcessor.js: improved multi-coin support
paymentProcessor.js: added minConfShield and minConfPayout variables
paymentProcessor.js: updated coin network stat caching
paymentProcessor.js: improved operation id handling when shielding coins
paymentProcessor.js: updated coin network stat caching
paymentProcessor.js: updated payment stat collection in redis
miner_stats.html: removed ZEC references

### CODE REVIEW

**Comment by hellcatz** [comment]
Note, this is a semi breaking change.
I changed the payments in redis to scoring for good reasons ;)
You must delete previous hash (not scoring) payments under coins in redis.

See Screenshot below:
image

**Comment by aayanl** [comment]
Reviewing

**Comment by sonicdx10** [comment]
Zdash team is going to update code (.5 or +) , maybe it can fix the user-stats-rpc issue

**Comment by aayanl** [comment]
I think instead of going nuclear with payments, just report null for old ones

**Comment by hellcatz** [comment]
We'll need to specifically test if this can be accomplished (backwards compatible). If no one else can, I may have time this weekend.

**Comment by sennevb** [comment]
Does this one fix the issue that komodo cant be used together with zcash??

**Comment by sonicdx10** [comment]
That it's already fixed on actual branch

**Comment by sennevb** [comment]
okay thanks, will test this out then..

**Comment by sennevb** [comment]
still getting this error when i enabled komodo:

still got this error:

/root/pool/node_modules/typeforce/index.js:154
throw tfSubError(e, i)
^
Error: Expected property "1" of type Satoshi, got Number NaN

**Comment by sonicdx10** [comment]
You should check closed issues just because it is a repeated issue already fixed

**Comment by hellcatz** [comment]
There is issues with the payment processor in z-nomp when running komodo that this PR resolves.
I'm am almost done testing the redis database concerns mentioned above. Preliminary results look perfect.

**Comment by hellcatz** [comment]
Redis does not have issue storing new format with old format.
image

New JSON API payments  output `../api/payments`  JSON output is valid with both formats.
image

From my testing on zcash_testnet, there is no issues with redis.
This is not a breaking change as I originally assumed 👍

**Comment by sennevb** [comment]
merge merge ;-)

**Pull request merged**
