### PR TITLE
Add a balances page

### PR DESCRIPTION
**Pull request by aayanl**
Most of the code came from https://bitcointalk.org/index.php?topic=701200.0;all and https://github.com/UNOMP/unified-node-open-mining-portal

### CODE REVIEW

**Comment by joshuayabut** [comment]
Looking at this now.

**Comment by sennevb** [comment]
would be great! we need this!

**Comment by sennevb** [comment]
any update on this?

**Comment by aayanl** [comment]
I've been busy with other projects, the problem is that it doesn't show pending balances, just payments that were already sent

**Pull request closed without merging**
