### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by hellcatz**
Added miner_stats.html
Added worker stats api call to api.js
Added miner_stats.html page to website.js
Updated workers.html to support worker stat pages.
Do not log accepted shares to console in poolWorker.js
Removed worker and block charts from stats.html and stats.js
Updated stats.html to show found blocks
Major updates to paymentProcessor.js
* worker names now supported
* operation id monitoring
* prevent duplicate shielding operations
* payments tracking to redis
* duplicate invalid block handling
* updates to balance rounding
* coin network stats logging to redis

### CODE REVIEW

**Comment by aayanl** [comment]
Works well standalone, testing mpos soon

**Comment by wariner84** [comment]
Nice job,
I noticed at miners page  (after 100 confirmations), balance "Bal:" remains to 0 (I am referring to workers that do not reach min payouts)

**Comment by hellcatz** [comment]
Balance is only updated once payments are made.
If the miner does not have enough for payment, then payment amount is transferred to balance.
I will double check in next day.

**Comment by wariner84** [comment]
I checked with data from the database
zec pool
not show balance but they are registered on the database (yes I know the amount is transferred to balance after payment)

**Pull request merged**
